

services:
  db:
    image: postgres:16
    container_name: store_inventory_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data4 

volumes:
  pgdata:
            
